### ISSUE TITLE
ARP-UPDATE-METHOD

### ISSUE THREAD

**Issue by 79Fox** [AMS-IX/arpsponge#11]
The following parameter isn't correctly wrote in the man / perldoc:

  --arp-update-method**s**=.. - how to update neighbor ARP caches

and must be updated by: 

  --arp-update-method

**Comment by sbakker** [comment]
Good catch! Will fix, thanks.

**Comment by 79Fox** [comment]
Thank you for developing this package and made it open source. It will be very useful to us.

**Comment by sbakker** [comment]
Just out of curiosity, where will you be using this? It was originally developed for Internet Exchanges, so I'm curious if it has any use outside of that.

**Comment by 79Fox** [comment]
We precisely would like to implement this package on an IXP - FranceIX :-)

**Comment by sbakker** [comment]
Nice! I didn't recognise your affiliation from your handle. :-)

I was hoping that we could get rid of the sponge at some point, because it looked as if EVPN would solve the problem of broadcast ARPs. But I heard from LINX that they are using it on their EVPN network now as well. Indeed, the broadcast problem is solved for ARP queries for _known_ IP addresses, but not for unknown (such as unused) addresses; those will still be forwarded as broadcasts (like, when people ping sweep the whole exchange LAN).
